### ISSUE TITLE
最近出问题了吗

### ISSUE THREAD

**Issue by SnowClick** [iozephyr/Get_UJN_Lib_Seat#12]
昨天 前天  各有一个号预约失败，我认为是被抢了，今天所有的都请求失败。。

**Comment by SnowClick** [comment]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): seat.ujn.edu.cn:8443
Traceback (most recent call last):
  File "C:\Users\zcj96\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\zcj96\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\zcj96\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by SnowClick** [comment]
妈耶服务器炸了。。。

**Comment by hephyr** [comment]
做好日志模块
